export const REFS = {
  'question-3b': {
    weather: ['Older rocks are broken down by weathering and erosion into small particles called sediment.', 'Rain, frost and wind wear rocks down into fragments of sand, silt and clay.'],
    transport: ['The sediment is transported by rivers, wind, ice and sea currents.', 'Rivers carry the broken pieces of rock down to the sea.'],
    deposit: ['The sediment is deposited in layers called strata on the floor of seas and lakes.', 'When the river slows down it drops its load, which settles on the sea bed in layers.'],
    compact: ['The weight of the layers above compacts the sediment and squeezes out the water.', 'Over time the lower layers are pressed together by the pressure of the layers on top.'],
    cement: ['Minerals such as calcite and silica cement the grains together.', 'The particles are glued together by minerals dissolved in the water.'],
    lithify: ['The sediment is turned into solid rock in a process called lithification.', 'Over millions of years the loose sediment hardens into rock.'],
    sandstone: ['Sandstone is formed from grains of sand that were compacted and cemented together.', 'Sandstone formed when sand deposited by rivers or in deserts was buried and compressed.'],
    redDesert: ['Old Red Sandstone is red because iron in the sand oxidised in hot desert conditions.', 'The sandstone formed in hot dry desert conditions and iron oxide stained it red.'],
    limestone: ['Limestone is formed from the shells and skeletons of sea creatures that built up on the sea floor.', 'When marine organisms died their remains collected on the sea bed and became limestone.'],
    warmSea: ['Limestone formed in warm, clear, shallow tropical seas when Ireland was near the equator.', 'Ireland was covered by a warm shallow sea about 350 million years ago.'],
    caco3: ['Limestone is made mainly of calcium carbonate from the shells.'],
    shale: ['Shale is formed when fine mud and clay are compacted into thin layers.', 'Very fine particles of mud settle in calm water and harden into shale.'],
    fossils: ['Sedimentary rocks such as limestone often contain fossils of plants and animals.', 'The remains of creatures trapped in the layers can be preserved as fossils.'],
    time: ['The formation of sedimentary rock takes millions of years.'],
    uplift: ['The rocks were later folded and uplifted by plate movements so they are now on land.'],
    coal: ['Coal formed from the remains of plants in swamps that were buried and compressed.'],
    bedding: ['Sedimentary rocks have horizontal layers separated by bedding planes.'],
    sandEx: ['Old Red Sandstone is found in the MacGillycuddys Reeks in County Kerry.', 'The mountains of Munster such as the Galtees are made of sandstone.'],
    limeEx: ['Limestone can be seen in the Burren in County Clare.', 'The Central Lowlands of Ireland are made of limestone.'],
    shaleEx: ['Layers of shale can be seen at the Cliffs of Moher in County Clare.'],
  },
  'question-3c': {
    seismo: ['Seismographs record vibrations and small tremors in the ground.', 'Seismometers measure the movement of the ground to detect earthquakes.'],
    foreshock: ['Small tremors called foreshocks can warn that a larger earthquake will follow.'],
    gaps: ['Scientists study seismic gaps, sections of a fault that have not moved for a long time, as stress is building up there.', 'By studying the history and pattern of past earthquakes scientists can predict where the next one may occur.'],
    tilt: ['Tiltmeters measure the bulging or tilting of the ground as stress builds up.'],
    laser: ['Lasers and GPS satellites measure tiny movements of the ground along fault lines.'],
    radon: ['An increase in radon gas in wells may show that rocks are cracking before an earthquake.', 'Changes in the level of water in wells can be a sign of an earthquake.'],
    animals: ['Strange animal behaviour, such as restless dogs, has been reported before earthquakes.'],
    difficult: ['It is not possible to predict the exact time of an earthquake, only the areas at risk.'],
    build: ['Buildings are designed to sway and bend with the shaking so that they do not collapse.', 'Strict building codes make sure new buildings are earthquake proof.'],
    base: ['Rubber shock absorbers in the foundations absorb the movement of the ground.', 'Base isolation separates the building from the ground so it shakes less.'],
    damper: ['Tall buildings use counterweights on the roof to reduce swaying.'],
    bracing: ['Steel frames and cross bracing make buildings stronger.'],
    drills: ['People practise earthquake drills so they know to drop, cover and hold on.', 'Schools educate children on what to do during an earthquake.'],
    warning: ['Early warning systems send alerts to phones so trains can stop and people can take cover.'],
    emergency: ['Families keep emergency kits with food, water and a torch.', 'Emergency services are trained and ready to rescue people.'],
    shutoff: ['Gas and electricity are shut off automatically to prevent fires.'],
    zoning: ['Planners stop people building on soft ground which can turn to liquid during an earthquake.'],
    retrofit: ['Older buildings are retrofitted with steel braces to make them stronger.'],
    tsunami: ['Tsunami warning systems and sea walls protect coastal towns.'],
  }
};
export const TESTS = {
  'question-3b': [
    ['rocks get broken into tiny bits by the rain and frost over time', 'weather'],
    ['Erosion breaks down mountains into sand and mud', 'weather'],
    ['the bits are carried away by a river until they reach the ocean', 'transport'],
    ['wind blows the sand across the desert', 'transport'],
    ['and Remains of dead sea creatires build up on the sea floor', 'limestone'],
    ['the sediment settles at the bottom of the lake in flat beds', 'deposit'],
    ['Over time these sediments and rock remains compress and compact from sea pressure', 'compact'],
    ['all the layers on top squash the bottom ones', 'compact'],
    ['water seeps through and leaves minerals that stick the grains together', 'cement'],
    ['eventually it hardens and becomes solid rock', 'lithify'],
    ['Sandstone is made of sand that got pressed and glued together', 'sandstone'],
    ['It is red because of iron that rusted when it was a desert', 'redDesert'],
    ['Limestone comes from shells of tiny sea animals', 'limestone'],
    ['Ireland used to be under a warm tropical sea near the equator', 'warmSea'],
    ['shale is made from really fine mud', 'shale'],
    ['you can find fossils in limestone', 'fossils'],
    ['the Burren in Clare is limestone', 'limeEx'],
    ['MacGillycuddys reeks are made of old red sandstone', 'sandEx'],
    ['coal comes from old forests and swamps that got buried', 'coal'],
    ['It takes millions and millions of years', 'time'],
    ['Sedimentary rocks are rocks.', null],
    ['I like geography a lot', null],
    ['Sandstone is a rock.', null],
    ['Volcanoes erupt lava which cools into basalt', null],
    ['rocks are very important to people', null],
    ['Granite is formed from magma cooling slowly underground', null],
    ['Limestone is used to make cement for buildings', null],
  ],
  'question-3c': [
    ['seismographs pick up small vibrations in the earth', 'seismo'],
    ['little shakes before a big quake can be a warning sign', 'foreshock'],
    ['if a fault hasnt moved in ages its probably going to go soon', 'gaps'],
    ['the ground swells up a tiny bit before an earthquake and they measure this', 'tilt'],
    ['satellites track how much the plates are moving', 'laser'],
    ['radon gas comes out of the ground before a quake', 'radon'],
    ['dogs and cats act weird before earthquakes', 'animals'],
    ['you cant really say exactly when one will happen', 'difficult'],
    ['buildings in Japan are made to bend instead of breaking', 'build'],
    ['they put big rubber pads under buildings to soak up the shaking', 'base'],
    ['a huge weight at the top of skyscrapers stops them swinging', 'damper'],
    ['kids in school practise hiding under their desks', 'drills'],
    ['phones get an alert a few seconds before the shaking starts', 'warning'],
    ['people keep a kit with water and food ready', 'emergency'],
    ['the gas turns off by itself so fires dont start', 'shutoff'],
    ['old buildings get made stronger with steel', 'retrofit'],
    ['they build walls along the coast to stop tsunamis', 'tsunami'],
    ['Earthquakes are bad and they kill people', null],
    ['Seismographs are used.', null],
    ['The earth has tectonic plates that move', null],
    ['Japan has a lot of earthquakes', null],
    ['Volcanoes can also be predicted', null],
    ['I think earthquakes are scary', null],
  ]
};
