// Third set: written after all word-list changes, run once, never tuned against.
export const FRESH = {
  'question-3b': [
    ['Mechanical weathering like frost shattering breaks the rock into fragments', 'weather'],
    ['Rivers erode the land and carry sand and silt downstream', 'weather'],
    ['The sediment is carried by the river current to the sea', 'transport'],
    ['When rivers lose energy they deposit their load', 'deposit'],
    ['Over time thick layers of sediment accumulate on the sea floor', 'deposit'],
    ['The layers at the bottom are compressed by the weight above them', 'compact'],
    ['The pressure forces the water out from between the grains', 'compact'],
    ['Minerals in the water cement the particles together', 'cement'],
    ['Eventually the sediment hardens to form a sedimentary rock', 'lithify'],
    ['Sandstone is made when grains of sand are cemented together', 'sandstone'],
    ['Old Red Sandstone formed in desert conditions when Ireland was hot and dry', 'redDesert'],
    ['Sandstone can be found in the Macgillycuddys Reeks in Kerry', 'sandEx'],
    ['Limestone formed from the shells of dead sea creatures', 'limestone'],
    ['These creatures lived in warm shallow seas that covered Ireland', 'warmSea'],
    ['Limestone can be found in the Burren in Co. Clare', 'limeEx'],
    ['Limestone is made of calcium carbonate', 'caco3'],
    ['Shale is formed from mud and clay that was deposited in calm water', 'shale'],
    ['Shale can be seen at the Cliffs of Moher', 'shaleEx'],
    ['Limestone often contains fossils of shells and coral', 'fossils'],
    ['Sedimentary rocks are formed in horizontal layers called strata', 'deposit'],
    ['The rocks were uplifted by tectonic forces and exposed at the surface', 'uplift'],
    ['Coal is formed from compressed plant remains', 'coal'],
    ['Sedimentary rocks are very common in Ireland', null],
    ['Limestone is a very useful rock', null],
    ['Igneous rocks form from magma', null],
    ['The Burren is a beautiful place to visit', null],
    ['Sandstone is red', null],
    ['Rocks can be different colours', null],
  ],
  'question-3c': [
    ['Seismographs are used to detect small movements in the crust', 'seismo'],
    ['A series of small tremors may come before a larger earthquake', 'foreshock'],
    ['Scientists look at where earthquakes happened in the past to predict future ones', 'gaps'],
    ['A tiltmeter measures any bulging of the ground', 'tilt'],
    ['Lasers are used to measure movement along faults', 'laser'],
    ['Water levels in wells sometimes change before an earthquake', 'radon'],
    ['Unusual animal behaviour can be a sign an earthquake is coming', 'animals'],
    ['Its impossible to say exactly when an earthquake will strike', 'difficult'],
    ['Buildings are constructed to be earthquake proof', 'build'],
    ['Rubber shock absorbers are built into the foundations of buildings', 'base'],
    ['Steel cross bracing strengthens the walls of buildings', 'bracing'],
    ['A counterweight on the roof stops the building swaying', 'damper'],
    ['Schools hold earthquake drills so students know what to do', 'drills'],
    ['Warning systems alert people seconds before the shaking arrives', 'warning'],
    ['Families keep emergency kits with water and food', 'emergency'],
    ['Gas pipes automatically shut off during an earthquake to prevent fires', 'shutoff'],
    ['Old buildings are retrofitted to make them safer', 'retrofit'],
    ['Tsunami warning buoys are placed in the ocean', 'tsunami'],
    ['Planners avoid building on soft ground', 'zoning'],
    ['Earthquakes are very dangerous', null],
    ['The 2011 earthquake in Japan killed thousands', null],
    ['Earthquakes are measured on the Richter scale', null],
    ['Plates move apart at constructive boundaries', null],
    ['Many people die in earthquakes each year', null],
  ]
};
