// Written before any word-list changes; never tuned against.
export const HOLD = {
  'question-3b': [
    ['Weathering such as freeze thaw breaks rocks into smaller particles', 'weather'],
    ['the pieces of rock are washed down rivers into the sea', 'transport'],
    ['glaciers also carry huge amounts of rock debris', 'transport'],
    ['When the river reaches the sea it slows down and drops the sediment', 'deposit'],
    ['layer upon layer of sediment builds up on the seabed', 'deposit'],
    ['the weight of the upper layers presses down on the lower ones', 'compact'],
    ['water is squeezed out of the sediment as it is compressed', 'compact'],
    ['calcite acts like a glue binding the particles together', 'cement'],
    ['Sandstone forms from sand grains deposited in deserts or rivers', 'sandstone'],
    ['Limestone is an organic rock formed from the skeletons of marine organisms', 'limestone'],
    ['the remains of coral and shellfish piled up on the ocean floor', 'limestone'],
    ['Ireland was located near the equator and covered by warm seas', 'warmSea'],
    ['The sandstone is red due to iron oxide', 'redDesert'],
    ['Old Red Sandstone is found in the mountains of Munster', 'sandEx'],
    ['Limestone is found in the Burren, Co Clare', 'limeEx'],
    ['Shale forms from very fine clay particles that are compressed', 'shale'],
    ['The Cliffs of Moher are made up of shale and sandstone', 'shaleEx'],
    ['Fossils of sea creatures are often found in limestone', 'fossils'],
    ['Coal was formed from dead plants in swamps', 'coal'],
    ['This process took place over millions of years', 'time'],
    ['Limestone is grey', null],
    ['There are three types of rock in the rock cycle', null],
    ['Marble is formed when limestone is heated', null],
    ['Sandstone is used for building houses', null],
    ['The rocks are very old', null],
  ],
  'question-3c': [
    ['A seismometer detects tremors in the earths crust', 'seismo'],
    ['Foreshocks often occur before a major earthquake', 'foreshock'],
    ['Areas along plate boundaries that have been quiet for a long time are most at risk', 'gaps'],
    ['Instruments called tiltmeters detect changes in the slope of the land', 'tilt'],
    ['GPS is used to monitor movement along the San Andreas fault', 'laser'],
    ['Levels of radon gas in groundwater increase before an earthquake', 'radon'],
    ['Animals such as toads have been seen leaving an area before an earthquake', 'animals'],
    ['Scientists still cannot predict the exact time an earthquake will occur', 'difficult'],
    ['Buildings are built with flexible steel frames so they can sway', 'build'],
    ['Base isolators made of rubber and steel are placed under buildings', 'base'],
    ['Skyscrapers have mass dampers to reduce the swaying', 'damper'],
    ['In Japan earthquake drills are held every year on Disaster Prevention Day', 'drills'],
    ['People are taught to drop, cover and hold on', 'drills'],
    ['An early warning system sends text messages before the shaking reaches a city', 'warning'],
    ['Emergency supplies such as water and first aid kits are stored', 'emergency'],
    ['Building on reclaimed land is avoided because of liquefaction', 'zoning'],
    ['Sea walls protect against tsunamis', 'tsunami'],
    ['Earthquakes happen at plate boundaries', null],
    ['The Richter scale measures earthquakes', null],
    ['Haiti had a big earthquake in 2010', null],
    ['Earthquakes cause a lot of damage', null],
    ['Earthquakes cannot be stopped', null],
  ]
};
